### ISSUE TITLE
Typo in the BOM list

### ISSUE THREAD

**Issue by Mu0n** [lampmerchant/tashrecorder#3]
location: https://github.com/lampmerchant/tashrecorder/tree/main/pcb 

the 680 pF film capacitor is called C8 in the list, but it should be C6 instead.

C8 is elsewhere and is an electrolytic cap.

**Comment by demik** [comment]
My bad. Fixed with PR #4

**Comment by lampmerchant** [comment]
Merged.  Thanks for pointing it out.
